### ISSUE TITLE
dec.time vs LZMA

### ISSUE THREAD

**Issue by Colibrow** [Calorado/Strider#1]
Hi, I notice that strider used Lz77+rANS implementation for better compression compared with Lzma but the decompress used almost twice timed.

FYI, comparison based on level 9 in LZMA and level 10 in strider.

**Comment by Calorado** [comment]
In my tests decompression speed is twice that of LZMA, at least on x64 and with SSE2. With no simd it is on par. And level 10 is pretty much just a test for how much compression can be achieved, it's very slow.
![Sin título](https://user-images.githubusercontent.com/30199611/181809465-acc7ab7b-2c19-4639-9ee1-7c9da83ff1ad.png)
